theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

title: Eric Janofsky
author: Eric Janofsky
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geb5101h.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - jekyll-whiteglass.gemspec
  - screenshot.png
  - vendor

# Social media
twitter_username: geb5101h
github_username:  geb5101h
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:
comments: false
mathjax: true

google_analytics: UA-156801543-1
