remote_theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

  title: Eric Janofsky
  url: "ericjanofsky.com"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 3

google_analytics: G-F6TCD28Q7P
markdown: kramdown
mathjax: true
title: Eric Janofsky
email: ebjanofsky@gmail.com